import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import {
  attemptsExhausted,
  buildMeetingTitle,
  hsTime,
  mergeNotes,
  normalizeEmail,
  parseMeetingTime,
  renderSummaryBlock,
  resolveSince,
  splitName,
} from './pure.js';
import { makeInteraction, makeTranscript } from '../test-utils/fakes.js';

const fixture = <T>(name: string): T =>
  JSON.parse(
    readFileSync(
      new URL(`../../test/fixtures/${name}`, import.meta.url),
      'utf8',
    ),
  );

// Goldens were generated by running the Python implementation in mla-notes-sync
// (scripts/transcript_processing/hubspot_summary_sync.py on feature/v2); this port must match.
describe('parity with the Python implementation', () => {
  const blocks = fixture<
    Array<{ name: string; interaction: any; expected: string }>
  >('summary-blocks.json');
  it.each(blocks)('renderSummaryBlock: $name', (b) => {
    expect(renderSummaryBlock(b.interaction)).toBe(b.expected);
  });

  const merges = fixture<
    Array<{
      name: string;
      existing: string | null;
      block: string;
      id: string;
      expected: string;
    }>
  >('merge-notes.json');
  it.each(merges)('mergeNotes: $name', (m) => {
    expect(mergeNotes(m.existing, m.block, m.id)).toBe(m.expected);
  });

  const misc = fixture<any>('pure-functions.json');
  it.each(misc.split_name as any[])('splitName $in', (c) => {
    expect(splitName(c.in)).toEqual(c.out);
  });
  it.each(misc.normalize_email as any[])('normalizeEmail $in', (c) => {
    expect(normalizeEmail(c.in)).toBe(c.out);
  });
  it.each(misc.meeting_time as any[])(
    'parseMeetingTime $interaction $transcript',
    (c) => {
      const dt = parseMeetingTime(c.interaction, c.transcript);
      expect(dt ? hsTime(dt) : null).toBe(c.out);
    },
  );
  it.each(misc.title as any[])(
    'buildMeetingTitle $interaction $transcript',
    (c) => {
      expect(buildMeetingTitle(c.interaction, c.transcript)).toBe(c.out);
    },
  );
});

describe('renderSummaryBlock', () => {
  it('has markers, a Participant line, labels, and joins arrays', () => {
    const block = renderSummaryBlock(makeInteraction());
    expect(block.startsWith('<!-- mla-summary:i-1 -->')).toBe(true);
    expect(block.trimEnd().endsWith('<!-- /mla-summary -->')).toBe(true);
    expect(block).toContain('<b>Participant:</b> Jane Advisor (Jane@Firm.com)');
    expect(block).toContain('<b>Pain Points:</b> high fees, slow reporting');
  });

  it('escapes html and omits empty fields', () => {
    const block = renderSummaryBlock(
      makeInteraction({ summary: '<script>x</script>', pain_points: [] }),
    );
    expect(block).not.toContain('<script>');
    expect(block).toContain('&lt;script&gt;');
    expect(block).not.toContain('Pain Points');
  });
});

describe('mergeNotes', () => {
  it('replaces only its own block and preserves human text', () => {
    const own = renderSummaryBlock(makeInteraction({ summary: 'old' }));
    const other = renderSummaryBlock(
      makeInteraction({ id: 'i-2', summary: 'other' }),
    );
    const next = renderSummaryBlock(makeInteraction({ summary: 'new' }));
    const out = mergeNotes(
      `before\n${own}\nmiddle\n${other}\nafter`,
      next,
      'i-1',
    );
    expect(out).toContain('new');
    expect(out).not.toContain('Meeting Summary:</b> old');
    expect(out).toContain('other');
    expect(out.startsWith('before')).toBe(true);
    expect(out.trimEnd().endsWith('after')).toBe(true);
    expect(out.split('<!-- mla-summary:i-1 -->').length - 1).toBe(1);
  });

  it('treats regex metacharacters in the id literally', () => {
    const block = renderSummaryBlock(makeInteraction({ id: 'a.b+c' }));
    const out = mergeNotes(`x\n${block}`, block, 'a.b+c');
    expect(out.split('<!-- mla-summary:a.b+c -->').length - 1).toBe(1);
  });
});

describe('parseMeetingTime', () => {
  it('prefers the transcript meeting_date', () => {
    expect(hsTime(parseMeetingTime(makeInteraction(), makeTranscript())!)).toBe(
      '2026-10-05T17:00:00Z',
    );
  });
  it('date-only values are null, never midnight', () => {
    expect(
      parseMeetingTime(
        makeInteraction({ interaction_date: '2026-10-05' }),
        makeTranscript({ meeting_date: null }),
      ),
    ).toBeNull();
  });
});

describe('attemptsExhausted / resolveSince', () => {
  it('caps at max attempts unless forced', () => {
    const i = makeInteraction({ hubspot_sync_attempts: 5 });
    expect(attemptsExhausted(i, 5)).toBe(true);
    expect(attemptsExhausted(i, 5, true)).toBe(false);
    expect(
      attemptsExhausted(makeInteraction({ hubspot_sync_attempts: 4 }), 5),
    ).toBe(false);
  });
  it('resolveSince prefers the argument, then env, else refuses', () => {
    expect(
      resolveSince('2026-10-01', { HUBSPOT_PUSH_SINCE: '2026-09-01' }),
    ).toBe('2026-10-01');
    expect(resolveSince(undefined, { HUBSPOT_PUSH_SINCE: '2026-09-01' })).toBe(
      '2026-09-01',
    );
    expect(() => resolveSince(undefined, {})).toThrow(/HUBSPOT_PUSH_SINCE/);
  });
});
